# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-cloud.yml if you use the "cloud" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

# Spring boot properties
spring:
  main:
    show-banner: false
  messages:
    basename: classpath:/i18n/messages
  mvc:
    favicon:
      enabled: false
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:}:${DB_PORT:3306}/${DB_DATABASE:}?useUnicode=true&characterEncoding=utf8&useSSL=false
    name: ${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    continueOnError: true
    initialize: false
    initialSize: 0
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 5000
    minIdle: 0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
    
server:
  port: ${port:8084}
  contextPath: /
  
